openapi: 3.0.0
info:
  title: PulgaShop API - Carrito y Órdenes
  description: API para gestión de carrito de compras y órdenes en PulgaShop
  version: 1.0.0
  contact:
    name: Javier-Rivera2311
    url: https://github.com/Javier-Rivera2311
servers:
  - url: http://localhost:3000
    description: Servidor de desarrollo
paths:
  /carrito:
    get:
      tags:
        - Carrito
      summary: Obtener productos del carrito
      description: Retorna todos los productos en el carrito de compras
      responses:
        '200':
          description: Lista de productos en el carrito
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/ProductoCarrito'
        '500':
          description: Error interno del servidor
    post:
      tags:
        - Carrito
      summary: Agregar producto al carrito
      description: Agrega un producto al carrito de compras
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ProductoDto'
      responses:
        '201':
          description: Producto agregado exitosamente
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ProductoCarrito'
        '400':
          description: Datos inválidos
        '500':
          description: Error interno del servidor
    delete:
      tags:
        - Carrito
      summary: Vaciar carrito
      description: Elimina todos los productos del carrito
      responses:
        '200':
          description: Carrito vaciado exitosamente
        '500':
          description: Error interno del servidor
  /carrito/{id}:
    delete:
      tags:
        - Carrito
      summary: Eliminar producto del carrito
      description: Elimina un producto específico del carrito
      parameters:
        - name: id
          in: path
          required: true
          description: ID del producto a eliminar
          schema:
            type: integer
      responses:
        '200':
          description: Producto eliminado exitosamente
        '404':
          description: Producto no encontrado
        '500':
          description: Error interno del servidor
  /ordenes:
    get:
      tags:
        - Órdenes
      summary: Obtener todas las órdenes
      description: Retorna la lista de todas las órdenes
      responses:
        '200':
          description: Lista de órdenes
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Orden'
        '500':
          description: Error interno del servidor
    post:
      tags:
        - Órdenes
      summary: Crear nueva orden
      description: Crea una nueva orden a partir del carrito actual
      responses:
        '201':
          description: Orden creada exitosamente
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Orden'
        '400':
          description: Carrito vacío o datos inválidos
        '500':
          description: Error interno del servidor
  /ordenes/{id}:
    get:
      tags:
        - Órdenes
      summary: Obtener orden por ID
      description: Retorna una orden específica por su ID
      parameters:
        - name: id
          in: path
          required: true
          description: ID de la orden
          schema:
            type: integer
      responses:
        '200':
          description: Detalles de la orden
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Orden'
        '404':
          description: Orden no encontrada
        '500':
          description: Error interno del servidor
components:
  schemas:
    ProductoDto:
      type: object
      required:
        - nombre
        - precio
        - cantidad
      properties:
        nombre:
          type: string
          description: Nombre del producto
          example: "Laptop Gamer"
        precio:
          type: number
          format: float
          description: Precio del producto
          example: 999.99
        cantidad:
          type: integer
          description: Cantidad del producto
          minimum: 1
          example: 1
        descripcion:
          type: string
          description: Descripción del producto
          example: "Laptop para gaming con tarjeta gráfica dedicada"
    ProductoCarrito:
      type: object
      properties:
        id:
          type: integer
          description: ID único del producto en el carrito
          example: 1
        nombre:
          type: string
          description: Nombre del producto
          example: "Laptop Gamer"
        precio:
          type: number
          format: float
          description: Precio del producto
          example: 999.99
        cantidad:
          type: integer
          description: Cantidad del producto
          example: 1
        descripcion:
          type: string
          description: Descripción del producto
          example: "Laptop para gaming con tarjeta gráfica dedicada"
        subtotal:
          type: number
          format: float
          description: Subtotal (precio * cantidad)
          example: 999.99
    Orden:
      type: object
      properties:
        id:
          type: integer
          description: ID único de la orden
          example: 1
        fecha:
          type: string
          format: date-time
          description: Fecha de creación de la orden
          example: "2024-12-02T10:30:00Z"
        productos:
          type: array
          description: Lista de productos en la orden
          items:
            $ref: '#/components/schemas/ProductoCarrito'
        total:
          type: number
          format: float
          description: Total de la orden
          example: 1299.98
        estado:
          type: string
          description: Estado de la orden
          enum: [pendiente, procesando, enviada, entregada, cancelada]
          example: "pendiente"
tags:
  - name: Carrito
    description: Operaciones relacionadas con el carrito de compras
  - name: Órdenes
    description: Operaciones relacionadas con las órdenes de compra
